// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbgcmiocpqwyhshdbvzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZ2NtaW9jcHF3eWhzaGRidnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTY0MjEsImV4cCI6MjA2NDI3MjQyMX0.IFxGc9fUT6pNHbEUA_TTSBK3YRrW0SCKqahk68pOFxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);